# Generated by Django 3.0.5 on 2020-05-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200517_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.IntegerField(default=0, max_length=111),
        ),
    ]
