# Generated by Django 3.0.5 on 2020-05-18 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phone',
            new_name='phones',
        ),
    ]
