# Generated by Django 3.0.5 on 2020-05-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20200518_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='phones',
            new_name='phone',
        ),
    ]
