# Generated by Django 3.0.5 on 2020-05-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20200518_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
